In [59]:
#Create an NxN square matrix (table) of random numbers between 0 and 100.

import numpy as np
from numpy import random

arr1=np.zeros((3,4)) #Crea un array de "0"
arr2=np.ones((2,3,4),dtype=np.int16) #Crea un array de "1"
arr3=np.arange(0,100,1) #Crea un array con n, n-1, paso. 
arr4=np.linspace(0,10,10) #Crea un array con valores uniformemente espaciados respecto a su cantidad de muestras.
arr5=np.full((3,3),1) #Array constante de un solo valor.
arr6=np.eye(2) #Crea arrays idénticos.

arr7 = random.randint(100, size=(11, 11)) #Array de 3x3 con números random de 0 a 99
print(arr7)



[[16 87 99 60 45 29  3 50 74 61 73]
 [79 80 98 41 12 58 97 23 70 90 14]
 [97 90 29 21  5 22 54 97 22 22  7]
 [ 1 50 19 18 61 72 33 37 64 29 52]
 [49 81 84 39 11 42 38 68 95 45 37]
 [ 1 35 28 84 10 89 47 45 23 73 74]
 [40 75 95 23 39 30 99 35 61  9 56]
 [ 1 89 82 52 34  2 24 69 72 86 29]
 [59 78 91 85  5 52 23 17 31 86 52]
 [38 83 22 60  3 80 28 44 66 88 20]
 [44 73 83 78 61 26 61 15 88 74 57]]
